# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: 'International Committee on Open Phytolith Science' # Website name
baseURL: 'https://openphyto.netlify.app/' # Website URL

############################
## PAGE OPTIONS
############################

cascade:
  # Docs folder options
  - _target:
      path: /course/**
    editable: true
    show_breadcrumb: true
  # Blog post folder options
  - _target:
      path: /post/**
    show_related: true

############################
## LANGUAGE
############################

defaultContentLanguage: en
languages:
  en:
  languageCode: en-us
  languageName: English
  weight: 1
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: International Committee on Open Phytolith Science
  description: Community building initiative and open science training for the Phytolith Community.
fr:
  languageCode: fr
  languageName: Français
  weight: 2
  contentDir: content/fr
  title: Comité international sur la science ouverte dans le phytolithe
  description: Initiative de renforcement de la communauté et formation en science ouverte pour la communauté Phytolith.
es:
  languageCode: es
  languageName: Spanish
  weight: 3
  contentDir: content/es
  title: Comité Internacional de Ciencia Abierta en Fitolitos
  description: Iniciativa de formación comunitaria y capacitación en ciencia abierta para la comunidad de fitolitos.


############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
