# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: International Committee on Open Phytolith Science
  params:
    description: Community building initiative and open science training for the Phytolith Community.
# fr:
#   languageCode: fr
#   contentDir: content/fr
#   title: Comité international sur la science ouverte dans le phytolithe
#   params:
#     description: Initiative de renforcement de la communauté et formation en science ouverte pour la communauté Phytolith.
# es:
#   languageCode: es
#   contentDir: content/es
#   title: Comité Internacional de Ciencia Abierta en Fitolitos
#   params:
#     description: Iniciativa de formación comunitaria y capacitación en ciencia abierta para la comunidad de fitolitos.



# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1


