# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1

# languages:
#   en:
#     baseURL: https://openphyto.netlify.app/
#     languageName: English
#     title: In English
#     weight: 1
#   fr:
#     baseURL: https://openphyto-fr.netlify.app/
#     languageName: Français
#     title: En Français
#     weight: 2
#   es:
#     baseURL: https://openphyto-es.netlify.app/
#     languageName: Español
#     title: En Español
#     weight: 3
